import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

const Footnote = ({ word, content, setHoveredWord }: { word: string, content: string, setHoveredWord: (w: string | null) => void }) => (
    <span 
        className="relative inline-block border-b border-[#737373] hover:border-white hover:text-white cursor-help transition-colors duration-200"
        onMouseEnter={() => setHoveredWord(content)}
        onMouseLeave={() => setHoveredWord(null)}
    >
        {word}
    </span>
);

export const OutputBrief = () => {
  const [activeContext, setActiveContext] = useState<string | null>(null);

  return (
    <section className="w-full py-32 flex flex-col items-center bg-[#050505]">
        <div className="mb-12 text-center">
            <h2 className="text-xs font-mono text-[#737373] uppercase tracking-widest mb-4">Output Generation</h2>
            <h3 className="text-4xl font-bold">The 3-Minute Brief</h3>
        </div>

        {/* The Document Container */}
        <div className="relative w-full max-w-2xl bg-[#0A0A0A] border border-[#1A1A1A] p-12 md:p-16 shadow-2xl">
            
            {/* Context Tooltip */}
            <AnimatePresence>
                {activeContext && (
                    <motion.div
                        initial={{ opacity: 0, x: 20 }}
                        animate={{ opacity: 1, x: 0 }}
                        exit={{ opacity: 0, scale: 0.9 }}
                        className="absolute -right-64 top-20 w-56 bg-[#F5F5F5] text-black p-4 text-xs font-mono border border-white z-50 shadow-xl"
                    >
                        <div className="uppercase font-bold mb-2 border-b border-black/20 pb-1">Source Material</div>
                        <p>{activeContext}</p>
                        <div className="mt-2 text-black/50">Rec: 14:02 PM via Slack</div>
                    </motion.div>
                )}
            </AnimatePresence>

            {/* Document Content */}
            <div className="font-serif text-[#333] text-lg leading-relaxed space-y-6 relative group">
                <div className="absolute top-0 left-0 w-1 h-full bg-[#1A1A1A]">
                    <motion.div 
                        className="w-full bg-white"
                        initial={{ height: "0%" }}
                        whileInView={{ height: "100%" }}
                        viewport={{ once: true }}
                        transition={{ duration: 4, ease: "linear" }}
                    />
                </div>

                <div className="pl-6">
                    <p className="transition-colors duration-700 hover:text-[#737373]">
                        <span className="text-[#F5F5F5]">Executive Summary:</span> Q3 trajectory indicates a 
                        <Footnote word=" 14% uplift" content="Revenue increased from $1.2M to $1.36M driven by Enterprise tier adoption." setHoveredWord={setActiveContext} /> 
                        in recurring revenue. However, operational overhead in the 
                        <Footnote word=" deployment pipeline" content="CI/CD failure rate increased by 4% due to new integration tests." setHoveredWord={setActiveContext} />
                        threatens to erode margins by end of quarter.
                    </p>
                    <p className="transition-colors duration-700 hover:text-[#737373]">
                        Strategic recommendation involves immediate reallocation of 
                        <Footnote word=" engineering resources" content="Shift 2 senior devs from Feature A to Stability Squad." setHoveredWord={setActiveContext} />
                        to stabilize core infrastructure before the holiday surge.
                    </p>
                    <p className="text-[#737373] text-sm mt-8 pt-8 border-t border-[#1A1A1A] font-mono">
                        Generated by Relia v2.4 • Confidential
                    </p>
                </div>
            </div>
        </div>
    </section>
  );
};